[tool.mypy]
ignore_missing_imports = true
exclude = "tests_e2e/"
strict = true
disallow_untyped_decorators = false
implicit_reexport = true
warn_unused_ignores = true
warn_unreachable = true
strict_equality = true

[[tool.mypy.overrides]]
module = "fasthtml.*"
ignore_missing_imports = true

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests", "tests_e2e"]
log_level = "INFO"
log_cli = true
asyncio_mode = "auto"

[tool.coverage.run]
source = ["src"]
omit = ["src/main.py"]

[tool.coverage.report]
exclude_lines = []
