[tool.mypy]
ignore_missing_imports = true
exclude = "tests/conftest\\.py"
strict = true
disallow_untyped_decorators = false
implicit_reexport = true
warn_unused_ignores = true


[[tool.mypy.overrides]]
module = "fasthtml.*"
ignore_missing_imports = true

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
log_level = "INFO"
log_cli = true

[tool.coverage.run]
source = ["src"]
omit = ["src/main.py"]

[tool.coverage.report]
exclude_lines = []
